# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsaAGIF0jXXKOI1pzq2pS8UYN-oSBEua
"""

!pip install pandas numpy scikit-learn matplotlib

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# Load IPO dataset
data = pd.read_csv("ipo_data.csv")

# Display first rows
print(data.head())

# Features and target
X = data.drop("Listing_Gain", axis=1)
y = data["Listing_Gain"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model Training
model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train_scaled, y_train)

# Predictions
y_pred = model.predict(X_test_scaled)

# Evaluation
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

# Feature Importance
importance = model.feature_importances_
for i, col in enumerate(X.columns):
    print(f"{col}: {importance[i]:.3f}")

# Predict New IPO
def predict_ipo(issue_size, sub_qib, sub_hni, sub_rii, gmp):
    input_data = np.array([[issue_size, sub_qib, sub_hni, sub_rii, gmp]])
    input_scaled = scaler.transform(input_data)
    gain = model.predict(input_scaled)
    return gain[0]

# Example Prediction
example = predict_ipo(1200, 35, 60, 15, 85)
print("Predicted Listing Gain %:", example)